name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run gradle wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run detekt static code analysis tool with Gradle
      run: ./gradlew detekt
